apiVersion: repositories.github.crossplane.io/v1alpha1
kind: BranchProtectionRule
metadata:
  name: example
spec:
  forProvider:
    owner: platform-test-org
    pattern: dev*
    repository: gabriel-1107-3
    isAdminEnforced: true
    bypassForcePushAllowances:
      - /Feggah
      - /platform-test-org/all-org-members
    bypassPullRequestAllowances:
      - /cnatan
    dismissesStaleReviews: true
    pushAllowances:
      - /dgmorales
      - /platform-test-org/platform-squad-writer
    requiredApprovingReviewCount: 3
    requiredStatusCheckContexts:
      - coverage/coveralls
    requiresCommitSignatures: true
    requiresConversationResolution: true
    requiresLinearHistory: true
    requiresStrictStatusChecks: true
  providerConfigRef:
    name: default
